name: CI devops 2024

on:
  # Trigger workflows on pushes to main and develop branches and on pull requests
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout code
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Use Temurin distribution for JDK

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean install
